/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppProjectsIndexRouteImport } from './routes/_app/projects/index'
import { Route as AuthCallbackGithubRouteRouteImport } from './routes/auth/callback/github/route'
import { Route as AppProjectsCreateIndexRouteImport } from './routes/_app/projects/create/index'
import { Route as AppProjectsProjectIdEditIndexRouteImport } from './routes/_app/projects/$projectId/edit/index'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProjectsIndexRoute = AppProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AuthCallbackGithubRouteRoute = AuthCallbackGithubRouteRouteImport.update({
  id: '/auth/callback/github',
  path: '/auth/callback/github',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProjectsCreateIndexRoute = AppProjectsCreateIndexRouteImport.update({
  id: '/projects/create/',
  path: '/projects/create/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProjectsProjectIdEditIndexRoute =
  AppProjectsProjectIdEditIndexRouteImport.update({
    id: '/projects/$projectId/edit/',
    path: '/projects/$projectId/edit/',
    getParentRoute: () => AppRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/callback/github': typeof AuthCallbackGithubRouteRoute
  '/projects': typeof AppProjectsIndexRoute
  '/projects/create': typeof AppProjectsCreateIndexRoute
  '/projects/$projectId/edit': typeof AppProjectsProjectIdEditIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/callback/github': typeof AuthCallbackGithubRouteRoute
  '/projects': typeof AppProjectsIndexRoute
  '/projects/create': typeof AppProjectsCreateIndexRoute
  '/projects/$projectId/edit': typeof AppProjectsProjectIdEditIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteRouteWithChildren
  '/auth/callback/github': typeof AuthCallbackGithubRouteRoute
  '/_app/projects/': typeof AppProjectsIndexRoute
  '/_app/projects/create/': typeof AppProjectsCreateIndexRoute
  '/_app/projects/$projectId/edit/': typeof AppProjectsProjectIdEditIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/callback/github'
    | '/projects'
    | '/projects/create'
    | '/projects/$projectId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/callback/github'
    | '/projects'
    | '/projects/create'
    | '/projects/$projectId/edit'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth/callback/github'
    | '/_app/projects/'
    | '/_app/projects/create/'
    | '/_app/projects/$projectId/edit/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AuthCallbackGithubRouteRoute: typeof AuthCallbackGithubRouteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/projects/': {
      id: '/_app/projects/'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AppProjectsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/auth/callback/github': {
      id: '/auth/callback/github'
      path: '/auth/callback/github'
      fullPath: '/auth/callback/github'
      preLoaderRoute: typeof AuthCallbackGithubRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/projects/create/': {
      id: '/_app/projects/create/'
      path: '/projects/create'
      fullPath: '/projects/create'
      preLoaderRoute: typeof AppProjectsCreateIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/projects/$projectId/edit/': {
      id: '/_app/projects/$projectId/edit/'
      path: '/projects/$projectId/edit'
      fullPath: '/projects/$projectId/edit'
      preLoaderRoute: typeof AppProjectsProjectIdEditIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppProjectsIndexRoute: typeof AppProjectsIndexRoute
  AppProjectsCreateIndexRoute: typeof AppProjectsCreateIndexRoute
  AppProjectsProjectIdEditIndexRoute: typeof AppProjectsProjectIdEditIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppProjectsIndexRoute: AppProjectsIndexRoute,
  AppProjectsCreateIndexRoute: AppProjectsCreateIndexRoute,
  AppProjectsProjectIdEditIndexRoute: AppProjectsProjectIdEditIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthCallbackGithubRouteRoute: AuthCallbackGithubRouteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
