/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppProjectsRouteRouteImport } from './routes/_app/projects/route'
import { Route as AuthCallbackGithubRouteRouteImport } from './routes/auth/callback/github/route'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProjectsRouteRoute = AppProjectsRouteRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AppRouteRoute,
} as any)
const AuthCallbackGithubRouteRoute = AuthCallbackGithubRouteRouteImport.update({
  id: '/auth/callback/github',
  path: '/auth/callback/github',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/projects': typeof AppProjectsRouteRoute
  '/auth/callback/github': typeof AuthCallbackGithubRouteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/projects': typeof AppProjectsRouteRoute
  '/auth/callback/github': typeof AuthCallbackGithubRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteRouteWithChildren
  '/_app/projects': typeof AppProjectsRouteRoute
  '/auth/callback/github': typeof AuthCallbackGithubRouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/projects' | '/auth/callback/github'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/projects' | '/auth/callback/github'
  id: '__root__' | '/' | '/_app' | '/_app/projects' | '/auth/callback/github'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AuthCallbackGithubRouteRoute: typeof AuthCallbackGithubRouteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/projects': {
      id: '/_app/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AppProjectsRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/auth/callback/github': {
      id: '/auth/callback/github'
      path: '/auth/callback/github'
      fullPath: '/auth/callback/github'
      preLoaderRoute: typeof AuthCallbackGithubRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteRouteChildren {
  AppProjectsRouteRoute: typeof AppProjectsRouteRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppProjectsRouteRoute: AppProjectsRouteRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthCallbackGithubRouteRoute: AuthCallbackGithubRouteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
